### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by jvanremoortere** [PascalKleindienst/october-blogsearch-extension#14]
Class 'System\Models\Parameters' not found
pkleindienst\blogsearch\components\SearchResult.php line 78

use System\Models\Parameter instead of Parameters

**Comment by PascalKleindienst** [comment]
Hi,
I tried to replicate the error but with no success. What version of october do you use?

Also could you change the following lines in /plugins/pkleindienst/blogsearch/components/SearchResult.php to see if they fix the error?
change line 9: `use System\Models\Parameters;` to `use System\Models\Parameter;`
change line 78: `$hasNewInspector = Parameters::get('system::core.build') >= 306;` to `$hasNewInspector = Parameter::get('system::core.build') >= 306;`

Regards,
Pascal

**Comment by PascalKleindienst** [comment]
Hi,
I've uploaded a new version of the plugin which removes the code because it's not needed anymore.
It requires October to be at least version 306

Regards,
Pascal
