### ISSUE TITLE
Error in October CMS Backend after installing

### ISSUE THREAD

**Issue by rafamem** [PascalKleindienst/october-blogsearch-extension#15]
Hello! This plugin have an error:

Class 'System\Models\Parameters' not found

/plugins/pkleindienst/blogsearch/components/SearchResult.php line 78

TYPE: Undefined

EXCEPTION: Symfony\Component\Debug\Exception\FatalErrorException

![screencapture-www-vsline-com-adm-cms-1469304286495](https://cloud.githubusercontent.com/assets/4790387/17080005/3bf61892-50ef-11e6-9726-ad0b02641747.png)

**Comment by PascalKleindienst** [comment]
Hi,
I tried to replicate the error but with no success. What version of october do you use?

Also could you change the following lines in /plugins/pkleindienst/blogsearch/components/SearchResult.php to see if they fix the error?
change line 9: `use System\Models\Parameters;` to `use System\Models\Parameter;`
change line 78: `$hasNewInspector = Parameters::get('system::core.build') >= 306;` to `$hasNewInspector = Parameter::get('system::core.build') >= 306;`

Regards,
Pascal

**Comment by rafamem** [comment]
I have the last version of October CMS. Can you tray in localhost with
xampp?

2016-08-01 6:16 GMT-04:00 Pascal Kleindienst notifications@github.com:

**Comment by PascalKleindienst** [comment]
Hi,
I've uploaded a new version of the plugin which removes the code because it's not needed anymore.
It requires October to be at least version 306

Regards,
Pascal

**Comment by rafamem** [comment]
Great! Thank you very much!! :-)

2016-08-01 10:56 GMT-04:00 Pascal Kleindienst notifications@github.com:
