### ISSUE TITLE
Bug: Posts.count in results not correct

### ISSUE THREAD

**Issue by LarryBarker** [PascalKleindienst/october-blogsearch-extension#19]
Expected behavior:

Display total post count on search result page.

Actual behavior:

When using the postsPerPage setting for the Search Result component, the post count only displays this number.

For example, if postsPerPage = 5, and there are actually 15 results across 3 pages, posts.count will only display 5 on the page, instead of 15.

**Comment by PascalKleindienst** [comment]
Hi,

that is the correct behavior. posts.count determines the number of posts on this page

What you are looking for is posts.total, which determines the total number of posts 😃 (https://laravel.com/api/5.5/Illuminate/Contracts/Pagination/LengthAwarePaginator.html#method_total)
