### ISSUE TITLE
Integrate within the blog plugin

### ISSUE THREAD

**Issue by FelixINX** [PascalKleindienst/october-blogsearch-extension#2]
Hi,

Have you tink of add your extension to the blog plugin?

This could be very nice.

**Comment by PascalKleindienst** [comment]
Hi,

it's a good idea to have it in the blog plugin itself. I'll create a pull request tomorrow :smiley: 
Thank you for your suggestion

**Comment by FelixINX** [comment]
Hi,

Do you plan to upload it to October CMS?

**Comment by PascalKleindienst** [comment]
Hi,

I there are some bugs when integrating directly to the blog plugin and I had not the time yet to fix them. So for now you have to use http://octobercms.com/plugin/pkleindienst-blogsearch

**Comment by FelixINX** [comment]
Ok, I will add it to my October theme to see how it's goes!

Thank you again.
