### ISSUE TITLE
Unable to get search results to render on results page

### ISSUE THREAD

**Issue by ram651** [PascalKleindienst/october-blogsearch-extension#3]
Even after properly including the searchResult component on the desired page, and having the searchForm properly route to the results page, I can't get any results to actually display. I've been scouring the plugin to see what issue there might be with having the searchParam posted and the SearchResult controller possibly not properly handling the post request, but I can't seem to find anything. Any ideas or similar issues during development/testing?

**Comment by PascalKleindienst** [comment]
Hi, 
I did not have the issue during development. But I installed it in a live system, and got the same issue. The problem was the cache, but I don't know exactly why.

Could you run 

```
php artisan cache:clear
```

and tell me if it worked?

**Comment by ram651** [comment]
That fixed it; I keep having to clear cache while developing other content on the site, but didn't make the connection that I might have to when implementing this new plugin.

Only caveat: pagination doesn't seem to work. I can make a search request that happens to match nearly all posts in the system, which right now displays out 4 pages of content with at most 10 posts per page. But, the links to pages 2+ do not work, and go to dead pages unrecognized by october.

I have the plugin referenced as such in the page header:

```
...other stuff...
url = "/news/results/:page?"
...other stuff...

[searchResult]
pageNumber = "{{ :page }}"
postsPerPage = "10"
noPostsMessage = "No search results"
sortOrder = "published_at desc"
categoryPage = "newscategory"
postPage = "newsitem"
```

As a note, the pagination for the standard Rainlab.Blog plugins, blogPosts and blogCategories, works properly and I haven't gone in detail yet to check if there's any significant difference between the implementation of Rainlab's pagination and yours.

**Comment by PascalKleindienst** [comment]
I'm glad that fixed it.
I'll look at the pagination problem now. I have simply copied it from the Blog plugin, but maybe I missed a part.

**Comment by PascalKleindienst** [comment]
I've found the problem. I throw a 404 when there is no post request -> bad idea with a pagination. I will update the plugin, so it only supports get requests like `search/:searchParam/:page?` that should fix the problem

**Comment by ram651** [comment]
I do remember reading that part of the code base, if only I had been as familiar with it to realize that would mess with pagination. Thanks for the support! First project to attach, glad to have done so.

**Comment by PascalKleindienst** [comment]
Version 1.0.4 is no online. Now the pagination works like it should :smiley:

**Comment by ram651** [comment]
yes, although now I believe the actual search functionality has broken, haha. Now the only results displayed are ALL posts regardless of search term..even after clearing application cache multiple times to be sure that a stored view wasn't being displayed.

I had gotten the desired functionality by simply commenting out the non-post method redirect statement from the 1.0.3 SearchResult controller, although I'm unsure of the potential ramifications of doing so.

edit: note: strange behavior because of my above mentioned stop-gap solution. the user is allowed to go back to a /news/result/:page url from another page on the site, and the previous search will have persisted, causing potential problems but maybe unforeseen ability for users to return to a search if they accidentally go to an undesired page?

**Comment by PascalKleindienst** [comment]
I had a error with the routing, maybe that was the problem, because the search is working fine in my tests ^^
Version 1.0.5 is now online

**Comment by ram651** [comment]
I'm still having the issue of search results only ever returning the entire result set of BlogPosts in my system :/ even after clearing cache, and looking through the changes made since 1.0.3, I just can't figure why. for now, I'm going to keep my system using 1.0.3 with my aforementioned change.

**Comment by PascalKleindienst** [comment]
Hmm, that's strange. Keep in mind that the Post Title **and** Content are used for the search, mybe your search term appears in all Post Contents?

**Comment by ram651** [comment]
I made sure not to. I have a few terms that I know the scale of their
result sets, and definitely getting different results when searching the
same thing between 1.0.3 and 1.0.4/5. I'll come back to it later

**Comment by PascalKleindienst** [comment]
Okay,
in version 1.0.3 could you

``` php
var_dump($this->searchParam);
```

after `$this->prepareVars` (https://github.com/PascalKleindienst/october-blogsearch-extension/blob/v1.0.3/components/SearchResult.php#L160)

and compare it with

``` php
var_dump($this->searchTerm);
```

after (https://github.com/PascalKleindienst/october-blogsearch-extension/blob/v1.0.5/components/SearchResult.php#L167) in Version 1.0.5 for the same search term?
Maybe your search term gets screwed up :confused:

**Comment by ghost** [comment]
Hello,
it wont work properly. 
Could you provide a _complete_ configuration example? 
My search string is always "NULL" and I don't know why.

Also: Line 169@SearchResult.php: 
If I change 
$searchTerm = \Input::get("search"); 
to 
$searchTerm = \Input::get("?search");
I'm getting at least my search string, but it messes up something else.

My Setup:
- single (static) page with searchResult component: /searchresults
- search term in configuration = ":search"
- URL example: /searchresults?search=whatever

Thanks in advance

**Comment by PascalKleindienst** [comment]
Hello,

my guess is that your url is wrong. You use `search` as a HTML Query String _(?search=...)_ which confuses October because it expects something like `/searchresults/whatever`. Thats why you get a result when your change `$searchTerm = \Input::get("search");` to `$searchTerm = \Input::get("?search");` 
So your page with the result component should have a url like: `/searchresults/:search/:page?`

An Example _(the search form component is optional and don't have to be on that page ;))_
![search-result](https://cloud.githubusercontent.com/assets/3470866/10275127/4b579f62-6b45-11e5-9874-9da4531d3c2e.png)

``` html
title = "Search Result"
url = "/blog/search/:search/:page?"
... other stuff

[searchResult]
searchTerm = "{{ :search }}"
hightlight = "1"
pageNumber = "{{ :page }}"
postsPerPage = "10"
noPostsMessage = "No posts found"
sortOrder = "published_at desc"
categoryPage = "blog-posts"
postPage = "blog-posts"

[searchForm]
resultPage = "blog/search"
==
<div class="container">
    <div class="row">
        <div class="page-header">
            <h2>Blog</h2>
        </div>
        <div class="col-sm-8">{% component 'searchResult' %}</div>
        <div class="col-sm-4">{% component 'searchForm' %}</div>
    </div>
</div>
```

I hope that fixes your problem :smiley: 
Regards Pascal

**Comment by ghost** [comment]
Hi, thanks for your help :)

Unfortunately the problem still exists:
- I changed the URL as you advised, no real change (see below)
- I tried "/searchresults/whatever" manually - it won't find anything
- I have no influence of the HTML query string. It happens automatically?
- When I've changed the URL to /searchresults/:search/:page? the result URL changes to: /searchresults/default?search=whatever
- Before it was: /searchresults?search=whatever 
- The URL "/searchresults/default" is also present in the (submit) form action.

I'm using the searchForm in a partial (sidebar) which gets included in the default layout.
The searchResult is on a separate (static) page which also uses the default layout (shouldn't be a problem IMO).

Even having the searchForm on the same page yields the same result.

Do you have any other ideas?

Thanks again for your help!

**Comment by PascalKleindienst** [comment]
Hi, 
it seems we're one step closer to find the problem :smiley: 

Having the searchForm in a sidebar partial and the result on a separate page is not a problem.

The submit URL in the form should be `/searchresults/default` which leads to the result url `/searchresults/default?search=whatever`. The result page should then redirect to `/searchresults/whatever`. It seems that the component does not redirect the page.

Have you changed `$searchTerm = \Input::get("?search");` back to `$searchTerm = \Input::get("search");`?
If you have and the problem still exists, could add `var_dump($searchTerm, $this->searchParam);` after `$searchTerm = ...`; and post the result

Regards
Pascal

**Comment by ghost** [comment]
Yes, I have changed it back after my first reply.
- var_dump(\Input::all()) as first statement inside onRun(): 
  **array(1) { ["?search"]=> string(8) "whatever" }**
- var_dump(\Input::get("search")) directly afterwards: 
  **NULL**
- var_dump(\Input::get("?search")) directly afterwards:
  **string(8) "whatever"**
- var_dump($this->searchTerm, $this->searchParam) directly afterwards:
  **NULL, NULL**
- var_dump($this->searchTerm, $this->searchParam) after "$this->prepareVars();": 
  **string(7) ":search", NULL**
- var_dump($searchTerm, $this->searchParam) after " $searchTerm = \Input::get("search");":
  **NULL, NULL**

As far as I can see the redirect at line 173 (+/- a line) won't happen because $searchTerm is always NULL :sob: 

Any ideas?

Cheers,
Mario

**Comment by PascalKleindienst** [comment]
Hi Mario,
that is very strange :confused: . You are right the searchterm doesn't get populated correctly

I tested it myself with a clean version of October and the plugin and I get the following (working) results:
- var_dump(\Input::all()) as first statement inside onRun():
  
  **array(1) { ["search"]=> string(8) "whatever" }**
- var_dump(\Input::get("search")) directly afterwards:
  
  **whatever**
- var_dump(\Input::get("?search")) directly afterwards:
  
  **NULL**
- var_dump($this->searchTerm, $this->searchParam) directly afterwards:
  
  **NULL, NULL**
- var_dump($this->searchTerm, $this->searchParam) after "$this->prepareVars();":
  
  **string(8) "whatever", string(6) "search"**
- var_dump($searchTerm, $this->searchParam) after " $searchTerm = \Input::get("search");":
  
  **string(8) "whatever", string(6) "search"**

Could you run `php artisan cache:clear`, maybe it is a caching Problem?
Another reason could be a plugin, try to disable all plugins except the blog and blogsearch plugin and test if it's working.
What version are you using both Plugin and October?

Regards,
Pascal

**Comment by ghost** [comment]
Cache cleared, no change.
All plugins except Blog and BlogSearch disabled, same.

Blog: 1.1.2
BlogSearch: 1.0.6
OctoberCMS: 298

The Blog plugin is working as intended, no problems there. I just don't use categories - but I don't think this is a problem (I've changed the categories-page to the same as the post-page in the component settings).

Thanks again!

Edit: Maybe it is a problem with nginx since the .htaccess won't work there. I'm investigating it...

**Comment by PascalKleindienst** [comment]
Okay, I have tested it with OctoberCMS 292 and 303 and it works. 
"I just don't use categories - but I don't think this is a problem " - That's not a problem, I have tested it with the default 404 page and it still works.

What PHP Version and what server (apache, nginx) + version do you use? Could you post your htaccess / server{} Content, maybe there's an error?

**Comment by ghost** [comment]
PHP 5.5.9 fastcgi, nginx 1.4.6

```
server {
        root /path/to/public/folder;
        index index.html index.htm index.php;

        server_name myserver.dev;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to index.php
                try_files $uri $uri/ /index.php?$query_string;
        }

        rewrite ^themes/.*/(layouts|pages|partials)/.*.htm /index.php break;
        rewrite ^bootstrap/.* /index.php break;
        rewrite ^config/.* /index.php break;
        rewrite ^vendor/.* /index.php break;
        rewrite ^storage/cms/.* /index.php break;
        rewrite ^storage/logs/.* /index.php break;
        rewrite ^storage/framework/.* /index.php break;
        rewrite ^storage/temp/protected/.* /index.php break;
        rewrite ^storage/app/uploads/protected/.* /index.php break;

        location ~/\.ht {
                deny all;
        }

        # pass the PHP scripts to FastCGI
        location ~ \.php$ {
                try_files $uri $uri/ /index.php?$query_string;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini

                # With php5-fpm:
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                include fastcgi_params;
        }
}

```

I've imported the .htaccess rules with http://winginx.com/en/htaccess.

**Comment by haubix** [comment]
I've removed the redirect except this block in /:
```
rewrite ^themes/.*/(layouts|pages|partials)/.*.htm /index.php break;
            rewrite ^bootstrap/.* /index.php break;
            rewrite ^config/.* /index.php break;
            rewrite ^vendor/.* /index.php break;
            rewrite ^storage/cms/.* /index.php break;
            rewrite ^storage/logs/.* /index.php break;
            rewrite ^storage/framework/.* /index.php break;
            rewrite ^storage/temp/protected/.* /index.php break;
            rewrite ^storage/app/uploads/protected/.* /index.php break;
```
Those redirects were already in place all the time. Sorry for the confusion.

**Comment by PascalKleindienst** [comment]
I have PHP + nginx myself and I cant find any errors in your config

I have now no clue why the plugin is behaving so strange with your configuration :disappointed: 
Sorry :(

**Comment by ghost** [comment]
I'm a step closer - I've changed the following in the nginx config:
Before: try_files $uri $uri/ /index.php$is_args$args;
After: try_files $uri $uri/ /index.php?$query_string;

var_dump($searchTerm,$this->searchParam);exit; after $searchTerm = \Input::get("search");
**string(8) "whatever" NULL**

So basically it gets redirected now.
But I don't understand the redirect:
$this->currentPageUrl([ $this->searchParam => urlencode($searchTerm)]) evaluates to /searchresults/default. Is this correct?

Thanks,
Mario

**Comment by ghost** [comment]
Eureka,
I got it running :smile: 

All I had to do is comment out this line in prepareVars():
$this->searchTerm = $this->page[ 'searchTerm' ] = urldecode($this->property('searchTerm'));

I don't know why but maybe you can see the bigger picture :wink:

Thanks a lot for your time and help - I really really appreciate it!

**Comment by PascalKleindienst** [comment]
Hi Mario,

glad that it's working now, but as I see it it should not work, because without the $this->searchTerm line, it should always find all posts!

Can you var_dump($this->paramName('searchTerm'), $this->property('searchTerm')); after prepareVars()? It seems there is an error because $this->searchParam and $this->searchTerm should not be NULL! We're getting one step closer to find the real problem :smiley: 

Can you show me your component configuration maybe there is the error for this behaviour
This part:

```
[searchResult]
searchTerm = "{{ :search }}"
hightlight = "1"
pageNumber = "{{ :page }}"
...
```

The Redirect: `$this->searchParam` contains the search url part you defined e.g. _:search_ and `urlencode($searchTerm)` contains to search value - e.g. _whatever_.
So the page _searchresult/default?search=whatever_ gets redirected to _searchresult/whatever_ because your url schema for the page is _searchresult/:search/:page?_.
But your `$this->searchParam`contains NULL (and I don't know why) so it gets redirected to _searchresult/default_

Regards,
Pascal

**Comment by ghost** [comment]
Yes, you were right - it shows all posts. Guess it was too late for me :disappointed: 

Result of var_dump: NULL, string(7) ":search"
URL: /searchresults/:search/:page?

Config (dunno where to find the config file):
Alias: searchResult
Search Term: :search
Page number: :page
Highlight Matches: [ ]
Posts per page: 10
No posts message: [...]
Post order: Published (descending)
Category page: post (/post/:slug)
Post page: post (/post/:slug)

Cheers

**Comment by EpicVoyage** [comment]
Couldn't the URL be `/searchresults/:search?/:page?` so that you can hit `/searchresults?search=text` and SearchResults.php can redirect to `/searchresults/text`? I was having a similar issue and this appears to be working for me.

**Comment by PascalKleindienst** [comment]
Hi Mario,

the page configuration is inside the html file in the /themes/your_theme/pages/searchresults.htm
Could you also try EpicVoyages suggestion, maybe that helps

@EpicVoyage thanks for your suggestion :smiley: 

Regards
Pascal

**Comment by ghost** [comment]
It works and now I'm feeling pretty dumb :angry: :smile:

Spot the difference:

Not Working:
![2](https://cloud.githubusercontent.com/assets/2040491/10375821/d5528684-6dfa-11e5-917a-da3cc66ba986.jpg)

Working:
![1](https://cloud.githubusercontent.com/assets/2040491/10375820/d54d2900-6dfa-11e5-90eb-ac8cbce13fdd.jpg)

Thanks alot for all of your time - I really appreciate it!

@EpicVoyage Unfortunately your solution wasn't the correct one for me :wink:, but thanks anyways for contributing!

**Comment by PascalKleindienst** [comment]
Hi,

I'm glad it is working now :smile: 
Only this simple things can cause so much trouble ^^

The difference between the two is explained here: https://octobercms.com/docs/cms/components#external-property-values

Regards
Pascal
