### ISSUE TITLE
Search is not searching $this ->page ->description = $this['post']->description;

### ISSUE THREAD

**Issue by aebian** [PascalKleindienst/october-blogsearch-extension#5]
Hi,

short question: Is there a solution that the plugin also searches for terms in the description? Now he searches only for terms in the headings

Regards,

~

**Comment by PascalKleindienst** [comment]
Hi,

first of all the post has no attribute named `description` only one named `excerpt`. As of now the plugin searches the title and the content of the post, but I could add an option to include the excerpt into the search as well.

Greetings

**Comment by aebian** [comment]
Would be nice. Thank you

**Comment by PascalKleindienst** [comment]
`excerpt` is included in version 1.0.6 and should be now online via october :smiley:

**Comment by aebian** [comment]
Works and works, thanks!
