### ISSUE TITLE
exclude some categories

### ISSUE THREAD

**Issue by surahmans** [PascalKleindienst/october-blogsearch-extension#6]
Hi, 

thank you for your great plugin.

I have a question, How to exclude some categories or category filter like rainlab.blog plugin?

thanks,

**Comment by PascalKleindienst** [comment]
Hi,

if I understand you correctly you want to show only search results for a specific category/categories?
That is not possible at the moment but it is a good idea :+1: 
I will add this as soons as I have the time :smile: 

Regards
Pascal

**Comment by surahmans** [comment]
wow, thank you Pascal!

I'm waiting for...

**Comment by PascalKleindienst** [comment]
The new version v1.1.0 is now online and adds the option to exclude categories from a search result and to restrict the search to a specific category :smiley:
