### ISSUE TITLE
display results from selected categories

### ISSUE THREAD

**Issue by skydiver** [PascalKleindienst/october-blogsearch-extension#9]
It's possible to add a parameter to "display results from only this category" ?

Got a search box for a specific category, and every time i create a new one i need to go back to the component and disable the recently created.

Also, on this search box i don't allow the user to select which category to search.

Thanks.

**Comment by PascalKleindienst** [comment]
Hi,

I could add that parameter in the next update. That's a good idea :+1: 

Regards,
Pascal

**Comment by skydiver** [comment]
Thanks for the new feature.

I think i found something wrong; when i print the post object, the categories object is empty.

Ex:
Printing `{{ post }}` will return:
```{
    "id":"43",
    "user_id":"2",
    "title":"Demo",
    "slug":"demo",
    "excerpt":"",
    "content":"demo post",
    "published_at":"2016-03-02 00:00:00",
    "published":"1",
    "created_at":"2016-03-13 20:20:14",
    "updated_at":"2016-03-13 20:29:39",
    "series_id":"5",
    "url":"http://demo.com",
    "summary":"Demo Post.",
    "has_summary":true,
   "categories":[]
}

```
```

**Comment by PascalKleindienst** [comment]
Hi, thanks for the info :+1: 
Should be fixed now :smiley:
